
site_name: Doc for Class 4
theme:
  name: "material"
plugins:
  - mkdocstrings
nav:
  - My Title: index.md
  - Tutorial: 
      - Description: tutorial.md
      - Functions: 
        - my_adder: my_adder.md
        - my_thermo_stat: my_thermo_stat.md
        - have_digits: have_digits.md
        - area_of_rectangle: area_of_rectangle.md
        - perimeter_of_rectangle: perimeter_of_rectangle.md

  - How-to Guide: 
    - Description: howtoguide.md
  - Reference: 
    - Reference: reference.md
  - Explanation: 
    - Explanation: explanation.md

theme: readthedocs